version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
